# VelocityASS 多线路服务器配置
# 此文件会在首次启动时根据Velocity的现有服务器自动生成
# 配置格式说明：
# servers:
#   服务器名称:
#     routes:
#       - address: "服务器地址:端口"
#         priority: 优先级数字(越小越优先)
#         enabled: true/false
#     auto-sort: true/false (是否根据延迟自动排序)
#     ping-interval: 30 (ping检测间隔，秒)
#     ping-timeout: 5000 (ping超时时间，毫秒)

servers:
  # 示例配置，首次启动时会被Velocity服务器配置替换
  example_server:
    routes:
      - address: "example.com:25565"
        priority: 1
        enabled: true
      # 为同一个服务器添加更多线路：
      # - address: "example2.com:25565"
      #   priority: 2
      #   enabled: true
    auto-sort: true
    ping-interval: 30
    ping-timeout: 5000